import fs from "node:fs";
const read=n=>fs.readFileSync(new URL(`./${n}`,import.meta.url),"utf8");
const html=read("index.html"),app=read("app.js"),db=read("db.js"),sync=read("sync.js"),finance=read("finance-store.js"),sw=read("sw.js"),css=read("styles-features.css");
const failures=[];const ok=(cond,msg)=>{if(!cond)failures.push(msg)};
ok(!/onclick\s*=/.test(html),"inline onclick remains in index.html");
ok(!/\.onclick\s*=/.test(app),"DOM onclick property remains in app.js");
ok(/script-src 'self'/.test(html)&&!/script-src[^;]*unsafe-inline/.test(html),"script CSP still permits unsafe-inline");
ok(/const APP_VERSION="1\.2\.0"/.test(app),"app version is not 1.2.0");
ok(/accountingMode:"manual-allocation"/.test(finance),"manual income allocation mode missing");
ok(/recordIncomeAtomic[\s\S]*db\.transaction\(\["transactions","incomeAllocations"\]/.test(finance),"income recording still mutates account balances before approval");
ok(/confirmAllocationAtomic\(allocationId,partsOverride=null\)/.test(finance),"editable allocation confirmation missing");
ok(/updateExpenseAtomic/.test(app)&&/updateIncomeAtomic/.test(app)&&/deleteFinancialTransactionAtomic/.test(app),"edit/delete finance actions missing");
ok(/expenseDescriptionSheet/.test(html)&&/saveExpenseDescription/.test(app),"expense description step missing");
ok(/amountCategory==="cigarette"/.test(app),"cigarette description bypass missing");
ok(/workSourceSelect/.test(html)&&/legacy-work-tabs/.test(css),"clean work source selector missing");
ok(/settings-collapse/.test(html)&&/settings-collapse/.test(css),"collapsed settings groups missing");
ok(/db\.transaction\(\["accounts","transactions"\],"readwrite"\)/.test(finance),"atomic multi-store finance transaction missing");
ok(/dirty:true/.test(sync)&&/startup-pending/.test(sync),"persistent dirty sync missing");
ok(/CLOUD_CONFLICT/.test(sync)&&/lastRemoteSha/.test(sync),"cloud conflict detection missing");
ok(/AES-GCM/.test(sync),"encrypted cloud backup missing");
ok(/DB_NAME="nova_core_v06",DB_VERSION=3/.test(db),"database identity changed");
ok(/crypto\.randomUUID/.test(read("core.js")),"UUID generator missing");
ok(/pruneLogs/.test(db)&&/maxErrors=100/.test(db),"log pruning missing");
ok(/styles-features\.css\?v=120/.test(html),"feature stylesheet cache version not updated");
ok(/mia-v120-manual-allocation-clean-ui/.test(sw),"service worker cache version not updated");
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const dup=ids.filter((x,i)=>ids.indexOf(x)!==i);ok(dup.length===0,`duplicate HTML ids: ${[...new Set(dup)].join(",")}`);
if(failures.length){console.error("MIA QA FAILED\n- "+failures.join("\n- "));process.exit(1)}
console.log("MIA v1.2.0 QA PASSED — manual allocation, editable transactions, expense description and clean UI checks passed.");
