import fs from "node:fs";
const read=n=>fs.readFileSync(new URL(`./${n}`,import.meta.url),"utf8");
const html=read("index.html"),app=read("app.js"),db=read("db.js"),sync=read("sync.js"),finance=read("finance-store.js"),sw=read("sw.js"),css=read("styles-features.css"),manifest=read("manifest.json");
const failures=[];const ok=(cond,msg)=>{if(!cond)failures.push(msg)};
ok(!/onclick\s*=/.test(html),"inline onclick remains in index.html");
ok(!/\.onclick\s*=/.test(app),"DOM onclick property remains in app.js");
ok(/script-src 'self'/.test(html)&&!/script-src[^;]*unsafe-inline/.test(html),"script CSP still permits unsafe-inline");
ok(/const APP_VERSION="1\.3\.0"/.test(app),"app version is not 1.3.0");
ok(/MIA v1\.3\.0/.test(html)&&/MIA v1\.3\.0/.test(manifest),"visible/manifest version not updated");
ok(/accountingMode:"manual-allocation"/.test(finance),"manual income allocation mode missing");
ok(/recordIncomeAtomic[\s\S]*db\.transaction\(\["transactions","incomeAllocations"\]/.test(finance),"income recording still mutates account balances before approval");
ok(/confirmAllocationAtomic\(allocationId,partsOverride=null\)/.test(finance),"editable allocation confirmation missing");
ok(/quickInterpretSheet/.test(html)&&/analyzeQuick/.test(app)&&/confirmQuickInterpretation/.test(app),"MIA understanding preview is missing");
ok(/expenseDescriptionSheet/.test(html)&&/مرحله ۲ از ۲/.test(html)&&/amountCategory==="cigarette"/.test(app),"guided expense description flow is incomplete");
ok(/transactionDetailSheet/.test(html)&&/openTransactionDetail/.test(app),"transaction detail-first interaction missing");
ok(!/\bconfirm\s*\(/.test(app),"native confirm dialog remains in app.js");
ok(/confirmSheet/.test(html)&&/askConfirm/.test(app),"friendly confirmation sheet missing");
ok(/next-action-card/.test(html)&&/completeNextHoorsunStage/.test(app),"next-action work UX missing");
ok(/workVisibilitySettings/.test(html)&&/visibleWorkSources/.test(app),"work source visibility controls missing");
ok(/<h1>تقویم<\/h1>/.test(html)&&/> رویداد<\/button>/.test(html),"planner terminology not simplified to calendar/event");
ok(/financeTotalBalance/.test(html)&&/allocationAttentionWrap/.test(html),"simplified finance overview missing");
ok(/home-balance-summary/.test(app)&&/home-account-line/.test(css),"compact home money snapshot missing");
ok(/advanced-settings/.test(html)&&/تنظیمات فنی GitHub/.test(html),"technical settings are not nested under advanced");
ok(/db\.transaction\(\["accounts","transactions"\],"readwrite"\)/.test(finance),"atomic multi-store finance transaction missing");
ok(/dirty:true/.test(sync)&&/startup-pending/.test(sync),"persistent dirty sync missing");
ok(/CLOUD_CONFLICT/.test(sync)&&/lastRemoteSha/.test(sync),"cloud conflict detection missing");
ok(/AES-GCM/.test(sync),"encrypted cloud backup missing");
ok(/DB_NAME="nova_core_v06",DB_VERSION=3/.test(db),"database identity changed");
ok(/styles-features\.css\?v=130/.test(html),"feature stylesheet cache version not updated");
ok(/mia-v130-user-friendly-redesign/.test(sw),"service worker cache version not updated");
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const dup=ids.filter((x,i)=>ids.indexOf(x)!==i);ok(dup.length===0,`duplicate HTML ids: ${[...new Set(dup)].join(",")}`);
const refs=[...app.matchAll(/\$\("([A-Za-z0-9_-]+)"\)/g)].map(m=>m[1]);
const idset=new Set(ids),missing=[...new Set(refs.filter(id=>!idset.has(id)))];ok(missing.length===0,`app references missing ids: ${missing.join(",")}`);
if(failures.length){console.error("MIA QA FAILED\n- "+failures.join("\n- "));process.exit(1)}
console.log("MIA v1.3.0 QA PASSED — user-friendly entry preview, guided expense flow, focused screens, detail-first editing and friendly confirmations verified.");
